---
- name: Ensure target .ssh directory exists
  ansible.builtin.file:
    path: "{{ user_home }}/.ssh"
    state: directory
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: "0700"
  tags:
    - ssh
    - install
